SolutionCategory.SINGLES=Singles
SolutionCategory.INTERSECTIONS=Intersections
SolutionCategory.SUBSETS=Subsets
SolutionCategory.BASIC_FISH=Basic Fish
SolutionCategory.FINNED_BASIC_FISH=(Sashimi) Finned Fish
SolutionCategory.FRANKEN_FISH=Franken Fish
SolutionCategory.FINNED_FRANKEN_FISH=Finned Franken Fish
SolutionCategory.MUTANT_FISH=Mutant Fish
SolutionCategory.FINNED_MUTANT_FISH=Finned Mutant Fish
SolutionCategory.SINGLE_DIGIT_PATTERNS=Single Digit Patterns
SolutionCategory.COLORING=Coloring
SolutionCategory.UNIQUENESS=Uniqueness
SolutionCategory.CHAINS_AND_LOOPS=Chains and Loops
SolutionCategory.WINGS=Wings
SolutionCategory.ALMOST_LOCKED_SETS=Almost Locked Sets
SolutionCategory.ENUMERATIONS=Enumerations
SolutionCategory.MISCELLANEOUS=Miscellaneous
SolutionCategory.LAST_RESORT=Last Resort
